-- This migration originally REVOKEd/GRANTed privileges on functions and a
-- `tenant_role` type (is_platform_admin, is_tenant_member, has_tenant_role,
-- is_user_approved, record_user_login_event, admin_get_user_login_history,
-- handle_new_user, set_tenant_id_from_membership, update_updated_at_column)
-- carried over from an earlier multi-tenant template. None of those objects
-- are created anywhere in this project's migration history, so replaying
-- this migration against a fresh database (supabase db reset, a new
-- environment) failed on its very first statement.
--
-- Neutralized to a no-op. The objects that do exist in this schema
-- (has_role, is_senate, etc.) have their own REVOKE/GRANT statements set
-- where they are actually created, later in this migration history.
